databases:
  - name: recipe_app
    databaseName: recipe_app_production
    user: recipe_app

services:
  - type: web
    name: recipe-app
    runtime: ruby
    buildCommand: "./bin/render-build.sh"
    startCommand: "bundle exec rails s"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: recipe_app_production
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false
